-- Catálogo de productos (F1-3) — sustituye el diccionario en memoria de
-- src/features/list/categorize.ts como fuente principal de categorización.
-- El diccionario en memoria se conserva como fallback offline-first (ver
-- src/features/list/catalog.ts): esta tabla se carga en segundo plano al
-- abrir la app y se fusiona con él, nunca lo sustituye por completo.

insert into public.products (locale, name, normalized, category_id) values
  -- ── produce ──────────────────────────────────────────────────────
  ('es', 'Tomate', 'tomate', 'produce'),
  ('es', 'Tomate cherry', 'tomate cherry', 'produce'),
  ('es', 'Lechuga', 'lechuga', 'produce'),
  ('es', 'Lechuga romana', 'lechuga romana', 'produce'),
  ('es', 'Cebolla', 'cebolla', 'produce'),
  ('es', 'Cebolleta', 'cebolleta', 'produce'),
  ('es', 'Patata', 'patata', 'produce'),
  ('es', 'Patata nueva', 'patata nueva', 'produce'),
  ('es', 'Boniato', 'boniato', 'produce'),
  ('es', 'Plátano', 'platano', 'produce'),
  ('es', 'Manzana', 'manzana', 'produce'),
  ('es', 'Manzana Golden', 'manzana golden', 'produce'),
  ('es', 'Naranja', 'naranja', 'produce'),
  ('es', 'Mandarina', 'mandarina', 'produce'),
  ('es', 'Pimiento rojo', 'pimiento rojo', 'produce'),
  ('es', 'Pimiento verde', 'pimiento verde', 'produce'),
  ('es', 'Zanahoria', 'zanahoria', 'produce'),
  ('es', 'Aguacate', 'aguacate', 'produce'),
  ('es', 'Ajo', 'ajo', 'produce'),
  ('es', 'Limón', 'limon', 'produce'),
  ('es', 'Fresas', 'fresas', 'produce'),
  ('es', 'Uvas', 'uvas', 'produce'),
  ('es', 'Sandía', 'sandia', 'produce'),
  ('es', 'Melón', 'melon', 'produce'),
  ('es', 'Pepino', 'pepino', 'produce'),
  ('es', 'Calabacín', 'calabacin', 'produce'),
  ('es', 'Berenjena', 'berenjena', 'produce'),
  ('es', 'Brócoli', 'brocoli', 'produce'),
  ('es', 'Coliflor', 'coliflor', 'produce'),
  ('es', 'Espinacas', 'espinacas', 'produce'),
  ('es', 'Acelgas', 'acelgas', 'produce'),
  ('es', 'Champiñones', 'champinones', 'produce'),
  ('es', 'Setas', 'setas', 'produce'),
  ('es', 'Kiwi', 'kiwi', 'produce'),
  ('es', 'Pera', 'pera', 'produce'),
  ('es', 'Melocotón', 'melocoton', 'produce'),
  ('es', 'Ciruela', 'ciruela', 'produce'),
  ('es', 'Apio', 'apio', 'produce'),
  ('es', 'Puerro', 'puerro', 'produce'),
  ('es', 'Remolacha', 'remolacha', 'produce'),
  ('es', 'Rábano', 'rabano', 'produce'),
  ('es', 'Calabaza', 'calabaza', 'produce'),
  ('es', 'Mango', 'mango', 'produce'),
  ('es', 'Piña', 'pina', 'produce'),
  ('es', 'Pomelo', 'pomelo', 'produce'),
  ('es', 'Higos', 'higos', 'produce'),
  ('es', 'Cerezas', 'cerezas', 'produce'),
  ('es', 'Arándanos', 'arandanos', 'produce'),
  ('es', 'Frambuesas', 'frambuesas', 'produce'),

  -- ── bakery ───────────────────────────────────────────────────────
  ('es', 'Pan', 'pan', 'bakery'),
  ('es', 'Pan de molde', 'pan de molde', 'bakery'),
  ('es', 'Pan integral', 'pan integral', 'bakery'),
  ('es', 'Barra de pan', 'barra de pan', 'bakery'),
  ('es', 'Baguette', 'baguette', 'bakery'),
  ('es', 'Bollería', 'bolleria', 'bakery'),
  ('es', 'Croissant', 'croissant', 'bakery'),
  ('es', 'Magdalenas', 'magdalenas', 'bakery'),
  ('es', 'Donuts', 'donuts', 'bakery'),
  ('es', 'Bizcocho', 'bizcocho', 'bakery'),
  ('es', 'Tortitas', 'tortitas', 'bakery'),
  ('es', 'Pan de pita', 'pan de pita', 'bakery'),
  ('es', 'Picos', 'picos', 'bakery'),
  ('es', 'Colines', 'colines', 'bakery'),

  -- ── dairy ────────────────────────────────────────────────────────
  ('es', 'Leche', 'leche', 'dairy'),
  ('es', 'Leche entera', 'leche entera', 'dairy'),
  ('es', 'Leche desnatada', 'leche desnatada', 'dairy'),
  ('es', 'Leche sin lactosa', 'leche sin lactosa', 'dairy'),
  ('es', 'Leche de avena', 'leche de avena', 'dairy'),
  ('es', 'Leche de soja', 'leche de soja', 'dairy'),
  ('es', 'Yogur', 'yogur', 'dairy'),
  ('es', 'Yogur griego', 'yogur griego', 'dairy'),
  ('es', 'Yogures', 'yogures', 'dairy'),
  ('es', 'Queso', 'queso', 'dairy'),
  ('es', 'Queso rallado', 'queso rallado', 'dairy'),
  ('es', 'Queso fresco', 'queso fresco', 'dairy'),
  ('es', 'Queso curado', 'queso curado', 'dairy'),
  ('es', 'Huevos', 'huevos', 'dairy'),
  ('es', 'Mantequilla', 'mantequilla', 'dairy'),
  ('es', 'Margarina', 'margarina', 'dairy'),
  ('es', 'Nata', 'nata', 'dairy'),
  ('es', 'Nata para cocinar', 'nata para cocinar', 'dairy'),
  ('es', 'Natillas', 'natillas', 'dairy'),
  ('es', 'Flan', 'flan', 'dairy'),
  ('es', 'Requesón', 'requeson', 'dairy'),
  ('es', 'Mascarpone', 'mascarpone', 'dairy'),

  -- ── meat ─────────────────────────────────────────────────────────
  ('es', 'Pollo', 'pollo', 'meat'),
  ('es', 'Pechuga de pollo', 'pechuga de pollo', 'meat'),
  ('es', 'Muslos de pollo', 'muslos de pollo', 'meat'),
  ('es', 'Ternera', 'ternera', 'meat'),
  ('es', 'Filete de ternera', 'filete de ternera', 'meat'),
  ('es', 'Cerdo', 'cerdo', 'meat'),
  ('es', 'Chuletas de cerdo', 'chuletas de cerdo', 'meat'),
  ('es', 'Carne picada', 'carne picada', 'meat'),
  ('es', 'Salchichas', 'salchichas', 'meat'),
  ('es', 'Bacon', 'bacon', 'meat'),
  ('es', 'Panceta', 'panceta', 'meat'),
  ('es', 'Costillas', 'costillas', 'meat'),
  ('es', 'Cordero', 'cordero', 'meat'),
  ('es', 'Pavo', 'pavo', 'meat'),
  ('es', 'Hamburguesas', 'hamburguesas', 'meat'),

  -- ── fish ─────────────────────────────────────────────────────────
  ('es', 'Pescado', 'pescado', 'fish'),
  ('es', 'Salmón', 'salmon', 'fish'),
  ('es', 'Atún', 'atun', 'fish'),
  ('es', 'Atún en lata', 'atun en lata', 'fish'),
  ('es', 'Gambas', 'gambas', 'fish'),
  ('es', 'Langostinos', 'langostinos', 'fish'),
  ('es', 'Merluza', 'merluza', 'fish'),
  ('es', 'Bacalao', 'bacalao', 'fish'),
  ('es', 'Sepia', 'sepia', 'fish'),
  ('es', 'Calamares', 'calamares', 'fish'),
  ('es', 'Mejillones', 'mejillones', 'fish'),
  ('es', 'Sardinas', 'sardinas', 'fish'),
  ('es', 'Lubina', 'lubina', 'fish'),
  ('es', 'Dorada', 'dorada', 'fish'),
  ('es', 'Pulpo', 'pulpo', 'fish'),

  -- ── deli ─────────────────────────────────────────────────────────
  ('es', 'Jamón', 'jamon', 'deli'),
  ('es', 'Jamón serrano', 'jamon serrano', 'deli'),
  ('es', 'Jamón york', 'jamon york', 'deli'),
  ('es', 'Chorizo', 'chorizo', 'deli'),
  ('es', 'Salchichón', 'salchichon', 'deli'),
  ('es', 'Mortadela', 'mortadela', 'deli'),
  ('es', 'Embutido', 'embutido', 'deli'),
  ('es', 'Lomo', 'lomo', 'deli'),
  ('es', 'Queso en lonchas', 'queso en lonchas', 'deli'),
  ('es', 'Paté', 'pate', 'deli'),

  -- ── frozen ───────────────────────────────────────────────────────
  ('es', 'Helado', 'helado', 'frozen'),
  ('es', 'Pizza congelada', 'pizza congelada', 'frozen'),
  ('es', 'Verdura congelada', 'verdura congelada', 'frozen'),
  ('es', 'Patatas fritas congeladas', 'patatas fritas congeladas', 'frozen'),
  ('es', 'Pescado congelado', 'pescado congelado', 'frozen'),
  ('es', 'Croquetas congeladas', 'croquetas congeladas', 'frozen'),
  ('es', 'Empanadillas congeladas', 'empanadillas congeladas', 'frozen'),
  ('es', 'Guisantes congelados', 'guisantes congelados', 'frozen'),
  ('es', 'Palitos de pescado', 'palitos de pescado', 'frozen'),

  -- ── pantry ───────────────────────────────────────────────────────
  ('es', 'Arroz', 'arroz', 'pantry'),
  ('es', 'Pasta', 'pasta', 'pantry'),
  ('es', 'Macarrones', 'macarrones', 'pantry'),
  ('es', 'Espaguetis', 'espaguetis', 'pantry'),
  ('es', 'Aceite', 'aceite', 'pantry'),
  ('es', 'Aceite de oliva', 'aceite de oliva', 'pantry'),
  ('es', 'Sal', 'sal', 'pantry'),
  ('es', 'Azúcar', 'azucar', 'pantry'),
  ('es', 'Harina', 'harina', 'pantry'),
  ('es', 'Lentejas', 'lentejas', 'pantry'),
  ('es', 'Garbanzos', 'garbanzos', 'pantry'),
  ('es', 'Alubias', 'alubias', 'pantry'),
  ('es', 'Conservas', 'conservas', 'pantry'),
  ('es', 'Tomate frito', 'tomate frito', 'pantry'),
  ('es', 'Mayonesa', 'mayonesa', 'pantry'),
  ('es', 'Ketchup', 'ketchup', 'pantry'),
  ('es', 'Mostaza', 'mostaza', 'pantry'),
  ('es', 'Vinagre', 'vinagre', 'pantry'),
  ('es', 'Caldo', 'caldo', 'pantry'),
  ('es', 'Sopa', 'sopa', 'pantry'),
  ('es', 'Cous cous', 'cous cous', 'pantry'),
  ('es', 'Quinoa', 'quinoa', 'pantry'),
  ('es', 'Miel', 'miel', 'pantry'),
  ('es', 'Especias', 'especias', 'pantry'),
  ('es', 'Pimienta', 'pimienta', 'pantry'),
  ('es', 'Canela', 'canela', 'pantry'),
  ('es', 'Levadura', 'levadura', 'pantry'),

  -- ── drinks ───────────────────────────────────────────────────────
  ('es', 'Agua', 'agua', 'drinks'),
  ('es', 'Agua con gas', 'agua con gas', 'drinks'),
  ('es', 'Zumo', 'zumo', 'drinks'),
  ('es', 'Zumo de naranja', 'zumo de naranja', 'drinks'),
  ('es', 'Cerveza', 'cerveza', 'drinks'),
  ('es', 'Vino', 'vino', 'drinks'),
  ('es', 'Refresco', 'refresco', 'drinks'),
  ('es', 'Cola', 'cola', 'drinks'),
  ('es', 'Café', 'cafe', 'drinks'),
  ('es', 'Café molido', 'cafe molido', 'drinks'),
  ('es', 'Té', 'te', 'drinks'),
  ('es', 'Batido', 'batido', 'drinks'),
  ('es', 'Tónica', 'tonica', 'drinks'),
  ('es', 'Horchata', 'horchata', 'drinks'),

  -- ── snacks ───────────────────────────────────────────────────────
  ('es', 'Patatas fritas', 'patatas fritas', 'snacks'),
  ('es', 'Chocolate', 'chocolate', 'snacks'),
  ('es', 'Chocolate con leche', 'chocolate con leche', 'snacks'),
  ('es', 'Galletas', 'galletas', 'snacks'),
  ('es', 'Caramelos', 'caramelos', 'snacks'),
  ('es', 'Chuches', 'chuches', 'snacks'),
  ('es', 'Frutos secos', 'frutos secos', 'snacks'),
  ('es', 'Almendras', 'almendras', 'snacks'),
  ('es', 'Cacahuetes', 'cacahuetes', 'snacks'),
  ('es', 'Palomitas', 'palomitas', 'snacks'),
  ('es', 'Aceitunas', 'aceitunas', 'snacks'),
  ('es', 'Gusanitos', 'gusanitos', 'snacks'),

  -- ── breakfast ────────────────────────────────────────────────────
  ('es', 'Cereales', 'cereales', 'breakfast'),
  ('es', 'Mermelada', 'mermelada', 'breakfast'),
  ('es', 'Muesli', 'muesli', 'breakfast'),
  ('es', 'Avena', 'avena', 'breakfast'),
  ('es', 'Tostadas', 'tostadas', 'breakfast'),
  ('es', 'Cacao en polvo', 'cacao en polvo', 'breakfast'),
  ('es', 'Café soluble', 'cafe soluble', 'breakfast'),

  -- ── cleaning ─────────────────────────────────────────────────────
  ('es', 'Lavavajillas', 'lavavajillas', 'cleaning'),
  ('es', 'Detergente', 'detergente', 'cleaning'),
  ('es', 'Papel higiénico', 'papel higienico', 'cleaning'),
  ('es', 'Lejía', 'lejia', 'cleaning'),
  ('es', 'Suavizante', 'suavizante', 'cleaning'),
  ('es', 'Friegasuelos', 'friegasuelos', 'cleaning'),
  ('es', 'Estropajo', 'estropajo', 'cleaning'),
  ('es', 'Bolsas de basura', 'bolsas de basura', 'cleaning'),
  ('es', 'Papel de cocina', 'papel de cocina', 'cleaning'),
  ('es', 'Limpiacristales', 'limpiacristales', 'cleaning'),
  ('es', 'Guantes de goma', 'guantes de goma', 'cleaning'),

  -- ── personal ─────────────────────────────────────────────────────
  ('es', 'Champú', 'champu', 'personal'),
  ('es', 'Gel de ducha', 'gel de ducha', 'personal'),
  ('es', 'Jabón', 'jabon', 'personal'),
  ('es', 'Pasta de dientes', 'pasta de dientes', 'personal'),
  ('es', 'Cepillo de dientes', 'cepillo de dientes', 'personal'),
  ('es', 'Desodorante', 'desodorante', 'personal'),
  ('es', 'Compresas', 'compresas', 'personal'),
  ('es', 'Tampones', 'tampones', 'personal'),
  ('es', 'Crema hidratante', 'crema hidratante', 'personal'),
  ('es', 'Cuchillas de afeitar', 'cuchillas de afeitar', 'personal'),

  -- ── baby ─────────────────────────────────────────────────────────
  ('es', 'Pañales', 'panales', 'baby'),
  ('es', 'Toallitas', 'toallitas', 'baby'),
  ('es', 'Potitos', 'potitos', 'baby'),
  ('es', 'Leche infantil', 'leche infantil', 'baby'),
  ('es', 'Papilla', 'papilla', 'baby'),

  -- ── pet ──────────────────────────────────────────────────────────
  ('es', 'Pienso', 'pienso', 'pet'),
  ('es', 'Comida para gatos', 'comida para gatos', 'pet'),
  ('es', 'Arena para gatos', 'arena para gatos', 'pet'),
  ('es', 'Snacks para perro', 'snacks para perro', 'pet')
on conflict (locale, normalized) do nothing;

insert into public.products (locale, name, normalized, category_id) values
  -- ── produce ──────────────────────────────────────────────────────
  ('en', 'Tomato', 'tomato', 'produce'),
  ('en', 'Cherry tomatoes', 'cherry tomatoes', 'produce'),
  ('en', 'Lettuce', 'lettuce', 'produce'),
  ('en', 'Romaine lettuce', 'romaine lettuce', 'produce'),
  ('en', 'Onion', 'onion', 'produce'),
  ('en', 'Spring onion', 'spring onion', 'produce'),
  ('en', 'Potato', 'potato', 'produce'),
  ('en', 'New potatoes', 'new potatoes', 'produce'),
  ('en', 'Sweet potato', 'sweet potato', 'produce'),
  ('en', 'Banana', 'banana', 'produce'),
  ('en', 'Apple', 'apple', 'produce'),
  ('en', 'Gala apple', 'gala apple', 'produce'),
  ('en', 'Orange', 'orange', 'produce'),
  ('en', 'Mandarin', 'mandarin', 'produce'),
  ('en', 'Red pepper', 'red pepper', 'produce'),
  ('en', 'Green pepper', 'green pepper', 'produce'),
  ('en', 'Carrot', 'carrot', 'produce'),
  ('en', 'Avocado', 'avocado', 'produce'),
  ('en', 'Garlic', 'garlic', 'produce'),
  ('en', 'Lemon', 'lemon', 'produce'),
  ('en', 'Strawberries', 'strawberries', 'produce'),
  ('en', 'Grapes', 'grapes', 'produce'),
  ('en', 'Watermelon', 'watermelon', 'produce'),
  ('en', 'Melon', 'melon', 'produce'),
  ('en', 'Cucumber', 'cucumber', 'produce'),
  ('en', 'Zucchini', 'zucchini', 'produce'),
  ('en', 'Eggplant', 'eggplant', 'produce'),
  ('en', 'Broccoli', 'broccoli', 'produce'),
  ('en', 'Cauliflower', 'cauliflower', 'produce'),
  ('en', 'Spinach', 'spinach', 'produce'),
  ('en', 'Chard', 'chard', 'produce'),
  ('en', 'Mushrooms', 'mushrooms', 'produce'),
  ('en', 'Wild mushrooms', 'wild mushrooms', 'produce'),
  ('en', 'Kiwi', 'kiwi', 'produce'),
  ('en', 'Pear', 'pear', 'produce'),
  ('en', 'Peach', 'peach', 'produce'),
  ('en', 'Plum', 'plum', 'produce'),
  ('en', 'Celery', 'celery', 'produce'),
  ('en', 'Leek', 'leek', 'produce'),
  ('en', 'Beet', 'beet', 'produce'),
  ('en', 'Radish', 'radish', 'produce'),
  ('en', 'Pumpkin', 'pumpkin', 'produce'),
  ('en', 'Mango', 'mango', 'produce'),
  ('en', 'Pineapple', 'pineapple', 'produce'),
  ('en', 'Grapefruit', 'grapefruit', 'produce'),
  ('en', 'Figs', 'figs', 'produce'),
  ('en', 'Cherries', 'cherries', 'produce'),
  ('en', 'Blueberries', 'blueberries', 'produce'),
  ('en', 'Raspberries', 'raspberries', 'produce'),

  -- ── bakery ───────────────────────────────────────────────────────
  ('en', 'Bread', 'bread', 'bakery'),
  ('en', 'Sliced bread', 'sliced bread', 'bakery'),
  ('en', 'Whole wheat bread', 'whole wheat bread', 'bakery'),
  ('en', 'Baguette', 'baguette', 'bakery'),
  ('en', 'Pastries', 'pastries', 'bakery'),
  ('en', 'Croissant', 'croissant', 'bakery'),
  ('en', 'Muffins', 'muffins', 'bakery'),
  ('en', 'Donuts', 'donuts', 'bakery'),
  ('en', 'Cake', 'cake', 'bakery'),
  ('en', 'Pancakes', 'pancakes', 'bakery'),
  ('en', 'Pita bread', 'pita bread', 'bakery'),
  ('en', 'Breadsticks', 'breadsticks', 'bakery'),

  -- ── dairy ────────────────────────────────────────────────────────
  ('en', 'Milk', 'milk', 'dairy'),
  ('en', 'Whole milk', 'whole milk', 'dairy'),
  ('en', 'Skim milk', 'skim milk', 'dairy'),
  ('en', 'Lactose-free milk', 'lactose-free milk', 'dairy'),
  ('en', 'Oat milk', 'oat milk', 'dairy'),
  ('en', 'Soy milk', 'soy milk', 'dairy'),
  ('en', 'Yogurt', 'yogurt', 'dairy'),
  ('en', 'Greek yogurt', 'greek yogurt', 'dairy'),
  ('en', 'Cheese', 'cheese', 'dairy'),
  ('en', 'Shredded cheese', 'shredded cheese', 'dairy'),
  ('en', 'Fresh cheese', 'fresh cheese', 'dairy'),
  ('en', 'Aged cheese', 'aged cheese', 'dairy'),
  ('en', 'Eggs', 'eggs', 'dairy'),
  ('en', 'Butter', 'butter', 'dairy'),
  ('en', 'Margarine', 'margarine', 'dairy'),
  ('en', 'Cream', 'cream', 'dairy'),
  ('en', 'Cooking cream', 'cooking cream', 'dairy'),
  ('en', 'Custard', 'custard', 'dairy'),
  ('en', 'Cottage cheese', 'cottage cheese', 'dairy'),
  ('en', 'Mascarpone', 'mascarpone', 'dairy'),

  -- ── meat ─────────────────────────────────────────────────────────
  ('en', 'Chicken', 'chicken', 'meat'),
  ('en', 'Chicken breast', 'chicken breast', 'meat'),
  ('en', 'Chicken thighs', 'chicken thighs', 'meat'),
  ('en', 'Beef', 'beef', 'meat'),
  ('en', 'Beef steak', 'beef steak', 'meat'),
  ('en', 'Pork', 'pork', 'meat'),
  ('en', 'Pork chops', 'pork chops', 'meat'),
  ('en', 'Ground beef', 'ground beef', 'meat'),
  ('en', 'Sausages', 'sausages', 'meat'),
  ('en', 'Bacon', 'bacon', 'meat'),
  ('en', 'Pork belly', 'pork belly', 'meat'),
  ('en', 'Ribs', 'ribs', 'meat'),
  ('en', 'Lamb', 'lamb', 'meat'),
  ('en', 'Turkey', 'turkey', 'meat'),
  ('en', 'Burgers', 'burgers', 'meat'),

  -- ── fish ─────────────────────────────────────────────────────────
  ('en', 'Fish', 'fish', 'fish'),
  ('en', 'Salmon', 'salmon', 'fish'),
  ('en', 'Tuna', 'tuna', 'fish'),
  ('en', 'Canned tuna', 'canned tuna', 'fish'),
  ('en', 'Shrimp', 'shrimp', 'fish'),
  ('en', 'Prawns', 'prawns', 'fish'),
  ('en', 'Hake', 'hake', 'fish'),
  ('en', 'Cod', 'cod', 'fish'),
  ('en', 'Cuttlefish', 'cuttlefish', 'fish'),
  ('en', 'Squid', 'squid', 'fish'),
  ('en', 'Mussels', 'mussels', 'fish'),
  ('en', 'Sardines', 'sardines', 'fish'),
  ('en', 'Sea bass', 'sea bass', 'fish'),
  ('en', 'Sea bream', 'sea bream', 'fish'),
  ('en', 'Octopus', 'octopus', 'fish'),

  -- ── deli ─────────────────────────────────────────────────────────
  ('en', 'Ham', 'ham', 'deli'),
  ('en', 'Serrano ham', 'serrano ham', 'deli'),
  ('en', 'Cooked ham', 'cooked ham', 'deli'),
  ('en', 'Chorizo', 'chorizo', 'deli'),
  ('en', 'Salami', 'salami', 'deli'),
  ('en', 'Mortadella', 'mortadella', 'deli'),
  ('en', 'Cold cuts', 'cold cuts', 'deli'),
  ('en', 'Pork loin', 'pork loin', 'deli'),
  ('en', 'Sliced cheese', 'sliced cheese', 'deli'),
  ('en', 'Pate', 'pate', 'deli'),

  -- ── frozen ───────────────────────────────────────────────────────
  ('en', 'Ice cream', 'ice cream', 'frozen'),
  ('en', 'Frozen pizza', 'frozen pizza', 'frozen'),
  ('en', 'Frozen vegetables', 'frozen vegetables', 'frozen'),
  ('en', 'Frozen fries', 'frozen fries', 'frozen'),
  ('en', 'Frozen fish', 'frozen fish', 'frozen'),
  ('en', 'Frozen croquettes', 'frozen croquettes', 'frozen'),
  ('en', 'Frozen dumplings', 'frozen dumplings', 'frozen'),
  ('en', 'Frozen peas', 'frozen peas', 'frozen'),
  ('en', 'Fish sticks', 'fish sticks', 'frozen'),

  -- ── pantry ───────────────────────────────────────────────────────
  ('en', 'Rice', 'rice', 'pantry'),
  ('en', 'Pasta', 'pasta', 'pantry'),
  ('en', 'Macaroni', 'macaroni', 'pantry'),
  ('en', 'Spaghetti', 'spaghetti', 'pantry'),
  ('en', 'Oil', 'oil', 'pantry'),
  ('en', 'Olive oil', 'olive oil', 'pantry'),
  ('en', 'Salt', 'salt', 'pantry'),
  ('en', 'Sugar', 'sugar', 'pantry'),
  ('en', 'Flour', 'flour', 'pantry'),
  ('en', 'Lentils', 'lentils', 'pantry'),
  ('en', 'Chickpeas', 'chickpeas', 'pantry'),
  ('en', 'Beans', 'beans', 'pantry'),
  ('en', 'Canned goods', 'canned goods', 'pantry'),
  ('en', 'Tomato sauce', 'tomato sauce', 'pantry'),
  ('en', 'Mayonnaise', 'mayonnaise', 'pantry'),
  ('en', 'Ketchup', 'ketchup', 'pantry'),
  ('en', 'Mustard', 'mustard', 'pantry'),
  ('en', 'Vinegar', 'vinegar', 'pantry'),
  ('en', 'Broth', 'broth', 'pantry'),
  ('en', 'Soup', 'soup', 'pantry'),
  ('en', 'Couscous', 'couscous', 'pantry'),
  ('en', 'Quinoa', 'quinoa', 'pantry'),
  ('en', 'Honey', 'honey', 'pantry'),
  ('en', 'Spices', 'spices', 'pantry'),
  ('en', 'Pepper', 'pepper', 'pantry'),
  ('en', 'Cinnamon', 'cinnamon', 'pantry'),
  ('en', 'Yeast', 'yeast', 'pantry'),

  -- ── drinks ───────────────────────────────────────────────────────
  ('en', 'Water', 'water', 'drinks'),
  ('en', 'Sparkling water', 'sparkling water', 'drinks'),
  ('en', 'Juice', 'juice', 'drinks'),
  ('en', 'Orange juice', 'orange juice', 'drinks'),
  ('en', 'Beer', 'beer', 'drinks'),
  ('en', 'Wine', 'wine', 'drinks'),
  ('en', 'Soda', 'soda', 'drinks'),
  ('en', 'Cola', 'cola', 'drinks'),
  ('en', 'Coffee', 'coffee', 'drinks'),
  ('en', 'Ground coffee', 'ground coffee', 'drinks'),
  ('en', 'Tea', 'tea', 'drinks'),
  ('en', 'Smoothie', 'smoothie', 'drinks'),
  ('en', 'Tonic water', 'tonic water', 'drinks'),
  ('en', 'Milkshake', 'milkshake', 'drinks'),

  -- ── snacks ───────────────────────────────────────────────────────
  ('en', 'Chips', 'chips', 'snacks'),
  ('en', 'Chocolate', 'chocolate', 'snacks'),
  ('en', 'Milk chocolate', 'milk chocolate', 'snacks'),
  ('en', 'Cookies', 'cookies', 'snacks'),
  ('en', 'Candy', 'candy', 'snacks'),
  ('en', 'Sweets', 'sweets', 'snacks'),
  ('en', 'Nuts', 'nuts', 'snacks'),
  ('en', 'Almonds', 'almonds', 'snacks'),
  ('en', 'Peanuts', 'peanuts', 'snacks'),
  ('en', 'Popcorn', 'popcorn', 'snacks'),
  ('en', 'Olives', 'olives', 'snacks'),

  -- ── breakfast ────────────────────────────────────────────────────
  ('en', 'Cereal', 'cereal', 'breakfast'),
  ('en', 'Jam', 'jam', 'breakfast'),
  ('en', 'Granola', 'granola', 'breakfast'),
  ('en', 'Oats', 'oats', 'breakfast'),
  ('en', 'Toast', 'toast', 'breakfast'),
  ('en', 'Cocoa powder', 'cocoa powder', 'breakfast'),
  ('en', 'Instant coffee', 'instant coffee', 'breakfast'),

  -- ── cleaning ─────────────────────────────────────────────────────
  ('en', 'Dish soap', 'dish soap', 'cleaning'),
  ('en', 'Detergent', 'detergent', 'cleaning'),
  ('en', 'Toilet paper', 'toilet paper', 'cleaning'),
  ('en', 'Bleach', 'bleach', 'cleaning'),
  ('en', 'Fabric softener', 'fabric softener', 'cleaning'),
  ('en', 'Floor cleaner', 'floor cleaner', 'cleaning'),
  ('en', 'Sponge', 'sponge', 'cleaning'),
  ('en', 'Garbage bags', 'garbage bags', 'cleaning'),
  ('en', 'Paper towels', 'paper towels', 'cleaning'),
  ('en', 'Glass cleaner', 'glass cleaner', 'cleaning'),
  ('en', 'Rubber gloves', 'rubber gloves', 'cleaning'),

  -- ── personal ─────────────────────────────────────────────────────
  ('en', 'Shampoo', 'shampoo', 'personal'),
  ('en', 'Shower gel', 'shower gel', 'personal'),
  ('en', 'Soap', 'soap', 'personal'),
  ('en', 'Toothpaste', 'toothpaste', 'personal'),
  ('en', 'Toothbrush', 'toothbrush', 'personal'),
  ('en', 'Deodorant', 'deodorant', 'personal'),
  ('en', 'Pads', 'pads', 'personal'),
  ('en', 'Tampons', 'tampons', 'personal'),
  ('en', 'Moisturizer', 'moisturizer', 'personal'),
  ('en', 'Razors', 'razors', 'personal'),

  -- ── baby ─────────────────────────────────────────────────────────
  ('en', 'Diapers', 'diapers', 'baby'),
  ('en', 'Wipes', 'wipes', 'baby'),
  ('en', 'Baby food', 'baby food', 'baby'),
  ('en', 'Formula', 'formula', 'baby'),
  ('en', 'Baby cereal', 'baby cereal', 'baby'),

  -- ── pet ──────────────────────────────────────────────────────────
  ('en', 'Pet food', 'pet food', 'pet'),
  ('en', 'Cat food', 'cat food', 'pet'),
  ('en', 'Cat litter', 'cat litter', 'pet'),
  ('en', 'Dog treats', 'dog treats', 'pet')
on conflict (locale, normalized) do nothing;
